services:
  - name: concurrent
    host: api
    port: 8000
    path: /api/v1
    injectCors: true
  - name: webui
    host: webui
    port: 80
    path: /web
    preservePath: true
  - name: url-summary
    host: summary
    port: 8080
    path: /summary
  - name: activitypub
    host: apbridge
    port: 8000
    path: /ap
    preservePath: true
    injectCors: true
  - name: webfinger
    host: apbridge
    port: 8000
    path: /.well-known
    preservePath: true
    injectCors: true
#  - name: mediaserver
#    host: mediaserver
#    port: 8000
#    path: /storage
